export default function () {
  this.transition(
    this.fromRoute('index'),
    this.toRoute('about'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('index'),
    this.toRoute('work'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('index'),
    this.toRoute('contact'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('about'),
    this.toRoute('work'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('about'),
    this.toRoute('contact'),
    this.use('fade'),
    this.reverse('fade')
  );
  this.transition(
    this.fromRoute('work'),
    this.toRoute('contact'),
    this.use('fade'),
    this.reverse('fade')
  );
}